<div class="hero theme-mixed">
    <h1>Welcome to Fun Quiz!</h1>
    <p class="hero-subtitle">Test your knowledge across 20+ exciting topics!</p>
</div>

<?php if (empty($session['user_name'])): ?>
<div class="registration-section">
    <h2 class="section-title">Let's Get Started!</h2>
    <form class="registration-form" id="registration-form" onsubmit="registerUser(event)">
        <div class="form-group">
            <label for="name">What's your name?</label>
            <input type="text" id="name" name="name" placeholder="Enter your name" required minlength="2" maxlength="50">
        </div>
        <div class="form-group">
            <label for="age">How old are you?</label>
            <input type="number" id="age" name="age" placeholder="Enter your age" required min="8" max="16">
            <span class="form-hint">This quiz is designed for ages 8-16</span>
        </div>
        <button type="submit" class="btn btn-primary btn-large">
            Start Quiz!
        </button>
    </form>
</div>
<?php else: ?>
<div class="welcome-back">
    <h2>Welcome back, <?= htmlspecialchars($session['user_name']) ?>!</h2>
    <p>Age: <?= (int)$session['user_age'] ?> years old</p>
    <div class="action-buttons">
        <a href="/play" class="btn btn-primary btn-large">Continue Playing</a>
        <button onclick="resetUser()" class="btn btn-secondary">Change User</button>
    </div>
</div>
<?php endif; ?>

<div class="topics-preview">
    <h2 class="section-title">20+ Exciting Topics Await!</h2>
    <div class="topics-grid">
        <?php
        $topics = \FunQuiz\QuizTopics::getAll();
        foreach ($topics as $slug => $topic):
        ?>
        <div class="topic-badge theme-<?= $slug ?>">
            <span class="topic-icon"><?= $topic['icon'] ?></span>
            <span class="topic-name"><?= $topic['name'] ?></span>
        </div>
        <?php endforeach; ?>
    </div>
</div>

<div class="features">
    <h2 class="section-title">Why Fun Quiz?</h2>
    <div class="features-grid">
        <div class="feature-card">
            <span class="feature-icon">🧒</span>
            <h3>Age-Appropriate</h3>
            <p>Questions tailored to your age group for the best learning experience</p>
        </div>
        <div class="feature-card">
            <span class="feature-icon">🤖</span>
            <h3>AI-Powered</h3>
            <p>Fresh questions generated by AI so you never see the same one twice!</p>
        </div>
        <div class="feature-card">
            <span class="feature-icon">🏆</span>
            <h3>Leaderboards</h3>
            <p>Compete with others and climb the global leaderboard</p>
        </div>
        <div class="feature-card">
            <span class="feature-icon">📱</span>
            <h3>Play Anywhere</h3>
            <p>Works on desktop, tablet, or mobile devices</p>
        </div>
    </div>
</div>

<script src="/js/registration.js"></script>
